[package]
name = "sonora"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
i18n.workspace = true
state.workspace = true
input.workspace = true
router.workspace = true
ui.workspace = true
views.workspace = true
workspace.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["rt"] }

[target.'cfg(windows)'.build-dependencies]
winresource.workspace = true
